sudo: true

language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      env: DISPLAY=:99.0

cache:
  directories:
  - $HOME/.m2

install: true

before_script:
 - sh -e ./before_script.sh

script:
 - mvn -f mydsl/pom.xml clean verify
